<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <?php if (!(new \App\Service\UserSession())->isAuthenticated() || $_SESSION['user']['role'] != ROLE_ADMIN): ?>
            
                <?php include "../templates/include/header.phtml";?>
                                
            <?php else: ?>
                
                <?php include "../templates/include/header_admin.phtml";?>

            <?php endif;?>

                        <li class="nav-item">
                            <a class="nav-link" href="#">Services</a>
                        </li>
                        <!-- Si l'utilisateur n'est pas connecté -->
                        <?php if (!(new \App\Service\UserSession())->isAuthenticated()): ?>
                            <li class="nav-item">
                                <a class="nav-link" href="/create-account">Espace client</a>
                            </li>
                        <?php else: ?>
                            <!-- Si l'utilisateur est connecté -->
                            <li class="nav-item">
                                <a class="nav-link" href="/connexion/logout">Déconnexion</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
</header>