<!-- Formulaire d'ajout de produit --> 

<!-- 

    - name
    - description
    - picture (champ texte dans un premier temps)
    - prix
    - stock
    - category (liste déroulante)
    - créateur (liste déroulante)

-->

<div class="col-12">
    <h1 class="text-center mb-3">Ajouter un produit</h1>
    <!-- Messages d'erreurs --> 
    <?php if (isset($errors) && !empty($errors)): ?>
        <?php foreach ($errors as $error): ?>
            <p class="alert alert-danger"><?=$error;?></p>
        <?php endforeach; ?>
    <?php endif; ?>
    <form action="/admin/product/new" method="POST">
        <div class="form-group">
            <label for="name">Nom</label>
            <input required type="text" class="form-control" id="name" name="name" value="">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea required class="form-control" id="description" name="description"></textarea>
        </div>
        <div class="form-group">
            <label for="picture_1">Image 1</label>
            <input type="text" class="form-control" id="picture_1" name="picture_1" value="">
        </div>
        <div class="form-group">
            <label for="picture_2">Image 2</label>
            <input type="text" class="form-control" id="picture_2" name="picture_2" value="">
        </div>
        <div class="form-group">
            <label for="picture_3">Image 3</label>
            <input type="text" class="form-control" id="picture_3" name="picture_3" value="">
        </div>
        <div class="form-group">
            <label for="picture_4">Image 4</label>
            <input type="text" class="form-control" id="picture_4" name="picture_4" value="">
        </div>
        <div class="form-group">
            <label for="price">Prix</label>
            <input required type="number" min="0" step="0.01" class="form-control" id="price" name="price">
        </div>
        <div class="form-group">
            <label for="stock">Stock</label>
            <input required type="number" min="0" class="form-control" id="stock" name="stock">
        </div>
        <div class="form-group">
            <label for="category">Catégorie</label>
            <select required class="form-control" id="category" name="category">
                <?php foreach ($categories as $category): ?>
                    <option value="<?=$category['id'];?>"><?=$category['label'];?></option>
                <?php endforeach;?>
            </select>
        </div>
        <div class="form-group">
            <label for="creator">Créateur</label>
            <select required class="form-control" id="creator" name="creator">
                <?php foreach ($creators as $creator): ?>
                    <option value="<?=$creator['id'];?>"><?=$creator['shop_name'];?></option>
                <?php endforeach;?>
            </select>
        </div>
        <button type="submit" class="btn btn-primary mb-3 d-block">Ajouter un produit</button>
    </form>
</div>