<form action="create_account.php" method="POST" class="col-5 d-flex flex-column justify-content-evenly border border-dark rounded">
    <h2 class="text-center mb-3 border-bottom py-2">Inscrivez-vous</h2>
    <?php if (isset($errors) && !empty($errors)): ?>
        <?php foreach ($errors as $errorAll): ?>
            <?php foreach ($errorAll as $error): ?>    
                <p class="alert alert-danger"><?=$error;?></p>
            <?php endforeach;?>
        <?php endforeach;?>
    <?php endif; ?>
    <div class="row">
        <div class="col">
            <input required type="text" class="form-control"name="firstname" id="firstname" placeholder="Prénom" value="<?=$firstname??'';?>">
        </div>
        <div class="col">
            <input required type="text" class="form-control" name="lastname" id="lastname" placeholder="Nom" value="<?=$lastname??'';?>">
        </div>
    </div>
    <div class="form-group mt-2">
        <label for="email">Adresse email</label>
        <input required type="email" class="form-control" name="email" id="email" aria-describedby="emailHelp" placeholder="Enter email" value="<?=$email??'';?>">
    </div>
    <div class="form-group">
        <label for="password">Mot de passe</label>
        <input required minlength="8" type="password" class="form-control" name="password" id="password" placeholder="Password">
    </div>
    <div class="form-group">
        <label for="confirmpass">Confirmation mot de passe</label>
        <input required minlength="8" type="password" class="form-control" name="confirmpass" id="confirmpass" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary mb-3 text-uppercase">S'inscrire</button>
</form>

<form action="login.php" method="POST" class="col-5 d-flex flex-column justify-content-evenly border border-dark rounded">
    <h2 class="text-center border-bottom py-2 mb-3">Connectez-vous</h2>
    <div class="form-group">
        <label for="email">Adresse email</label>
        <input required type="email" class="form-control" name="email" id="email" aria-describedby="emailHelp" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="password">Mot de passe</label>
        <input required type="password" class="form-control" name="password" id="password" placeholder="Password">
    </div>
    <div class="form-check mb-1">
        <input type="checkbox" class="form-check-input" name="stayConnected" id="stayConnected">
        <label class="form-check-label" for="stayConnected">Rester connecté</label>
    </div>
    <button type="submit" class="btn btn-primary text-uppercase">Se connecter</button>
</form>