<!-- Bootstrap Cards -->
<?php foreach($products as $product): ?>
    <div class="col-6 mb-5">
        <div class="card bg-light border-secondary mb-3">
            <a href="/product?productId=<?= $product['id'];?>">
                <img src="images/<?= $product['picture_1'];?>" class="card-img-top" alt="<?= $product['name'];?>">
            </a>
            <div class="card-body">
                <h5 class="card-title font-weight-bold">
                    <a href="/product?productId=<?= $product['id'];?>" class="text-body">
                        <?= $product['name'];?>
                    </a>
                </h5>
                <p class="card-text h5">Créateur : <?=$product['shop_name'];?></p>
                <p class="card-text h5">Prix : <?=\App\Service\Formatter::formatPrice($product['price']);?></p>
                <span class="badge badge-secondary mb-2"><?= $product['label'];?></span>
                <a href="#" class="btn btn-primary d-block">Ajouter au panier</a>
            </div>
        </div>
    </div>
<?php endforeach;?>