<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

        <title>Hello, world!</title>
    </head>
    <body class="bg-dark">

        <div class="container mt-5">
            <div class="row">
                <?php foreach($products as $product): ?>
                    <div class="col-6 mb-5">
                        <div class="card bg-light border-secondary mb-3">
                            <a href="product-details.php?prudctId=<?= $product['id'];?>">
                                <img src="images/<?= $product['picture'];?>" class="card-img-top" alt="<?= $product['name'];?>">
                            </a>
                            <div class="card-body">
                                <h5 class="card-title font-weight-bold">
                                    <a href="product-details.php?prudctId=<?= $product['id'];?>" class="text-body">
                                        <?= $product['name'];?>
                                    </a>
                                </h5>
                                <p class="card-text h5">Prix : <?= $product['price'];?> €</p>
                                <p class="card-text h5">Catégorie : <?= $product['label'];?></p>
                                <p class="card-text h5">Créateur : <?= $product['shop_name'];?></p>
                                <a href="#" class="btn btn-primary">Ajouter au panier</a>
                            </div>
                        </div>
                    </div>
                <?php endforeach;?>
            </div>
        </div>

        <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    </body>
</html>