<!-- Product Image -->
<aside class="col mr-3">
    <img src="images/<?=$productDetails['picture'];?>" alt="" class="w-30rem">
</aside>
<!-- Product Details -->
<section class="col text-center align-self-center">
    <h1><?=$productDetails['name'];?></h1>
    <span class="badge badge-secondary mb-2"><?= $productDetails['label'];?></span>
    <span class="badge badge-secondary mb-2"><?= $productDetails['price'];?> €</span>
    <span class="badge badge-secondary mb-2">Stock : <?= $productDetails['stock'];?></span>
    <span class="badge badge-secondary mb-2">Created by : <?= $productDetails['shop_name'];?></span>
    <p><?=nl2br($productDetails['description']);?></p>
</section>